export const api = {
  "apiUpdateContent": "/api/update-content",
  "apiNamaKabupaten": "/api/nama-kabupaten",
  "apiIndonesiaMap": "/api/indonesia-map",
  "apiGetDataByCandidate": "/api/get-data-by-candidate",
  "apiGetCandidate": "/api/get-candidate",
  "apiCopyData": "/api/copy-data",
  "apiUtilStore": "/api/util/store",
  "apiUtilGetCityValue": "/api/util/get-city-value",
  "apiUtilGetCandidate": "/api/util/get-candidate",
  "apiSeederProvince": "/api/seeder/province",
  "apiSeederEmotion": "/api/seeder/emotion",
  "apiSeederDataContent": "/api/seeder/data-content",
  "apiSeederCity": "/api/seeder/city",
  "apiSeederCityValue": "/api/seeder/city-value",
  "apiSeederCandidate": "/api/seeder/candidate",
  "apiSummaryGetWordCloud": "/api/summary/get-word-cloud",
  "apiSummaryGetTop10ProvinceByConversation": "/api/summary/get-top-10-province-by-conversation",
  "apiSummaryGetTop10DistrictByConversation": "/api/summary/get-top-10-district-by-conversation",
  "apiSummaryGetSourceOfMention": "/api/summary/get-source-of-mention",
  "apiSummaryGetNationWideChart": "/api/summary/get-nation-wide-chart",
  "apiPredictiveAiNationWideRating": "/api/predictive-ai/nation-wide-rating",
  "apiDevSyncWordCloud": "/api/dev/sync-word-cloud",
  "apiDevSyncSourceOfMention": "/api/dev/sync-source-of-mention",
  "apiDevSyncNationWideChart": "/api/dev/sync-nation-wide-chart",
  "apiB24B24Api": "/api/b24/b24-api"
}