#!/bin/bash

pull() {
    echo "ini aapa namanya"
}

push() {
    branch=$(git rev-parse --abbrev-ref HEAD)
    git add .
    echo "masukkan commitnya"
    read commit
    git commit -m "$commit"
    git push origin $branch
}

info() {

    echo "
    info:
    pull = untuk poull
    push = untuk push
    "

}

case $1 in
pull) pull ;;
push) push ;;
*) info ;;
esac

# branch=$(git rev-parse --abbrev-ref HEAD)
