import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import MyMain from "@/layouts/my_main";
import { Box } from "@mantine/core";
import { gradient } from "@/styles/gradient";
// import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Eagle Reignite</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box >
        <MyMain />
      </Box>
    </>
  );
}
